### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wailliam-x** [baas-pro/baas#1]
发生异常: [WinError 740] 请求的操作需要提升。
堆栈跟踪:
Traceback (most recent call last):
  File "launcher.py", line 141, in main
  File "launcher.py", line 90, in start_baas
  File "launcher.py", line 107, in start_baas_windows
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1416, in _execute_child
OSError: [WinError 740] 请求的操作需要提升。

**Comment by KilluaaaCHEN** [comment]
用管理员权限执行
