### ISSUE TITLE
开图6-1支线开始,无法进行代理

### ISSUE THREAD

**Issue by AryochiL** [baas-pro/baas#20]
v2.0.4  WARNING  12-24 15:44:05 │ 当前关卡状态为:side
v2.0.4  WARNING  12-24 15:44:05 │ 未通关支线，开始支线战斗
v2.0.4  INFO     12-24 15:44:05 │ click (645,511)
v2.0.4  CRITICAL 12-24 15:44:06 │ Exception occurred: 'side'
v2.0.4  CRITICAL 12-24 15:44:06 │ Stack trace:
Traceback (most recent call last):
  File "common\process.py", line 12, in baas_dashboard
  File "common\baas.py", line 183, in dashboard
  File "modules\exp\normal_task\exp_normal_task.py", line 78, in start
  File "modules\exp\normal_task\exp_normal_task.py", line 108, in start_fight
KeyError: 'side'

**Comment by KilluaaaCHEN** [comment]
v2.0.7会修复,过几天发布
