### ISSUE TITLE
日服MomoTalk任务时提示fail.png图片不存在

### ISSUE THREAD

**Issue by lllnnntt** [baas-pro/baas#21]
v2.0.3  CRITICAL 12-24 16:43:24 │ Exception occurred: 图片文件 F:\xz\baas\baas\_internal\assets/images\jp\fight\fail.png 不存在
v2.0.3  CRITICAL 12-24 16:43:24 │ Stack trace:
Traceback (most recent call last):
  File "common\process.py", line 12, in baas_dashboard
  File "common\baas.py", line 183, in dashboard
  File "modules\reward\momo_talk.py", line 39, in start
  File "modules\reward\momo_talk.py", line 93, in start_chat
  File "modules\reward\momo_talk.py", line 119, in begin_relationship
  File "modules\reward\momo_talk.py", line 131, in skip_plot
  File "common\image.py", line 202, in detect
  File "common\image.py", line 97, in compare_image
  File "common\image.py", line 252, in get_img_data
FileNotFoundError: 图片文件 F:\xz\baas\baas\_internal\assets/images\jp\fight\fail.png 不存在
![AXQN21L7$ZXC@P5@X MS}XN](https://github.com/baas-pro/baas/assets/53374856/0ae52a3d-280c-44c7-9500-af1165c0af82)

**Comment by KilluaaaCHEN** [comment]
版本过低,更新到v2.0.5
