### ISSUE TITLE
编队识别失败

### ISSUE THREAD

**Issue by AryochiL** [baas-pro/baas#3]
Traceback (most recent call last):
  File "common\process.py", line 12, in baas_dashboard
  File "common\baas.py", line 184, in dashboard
  File "modules\exp\normal_task\exp_normal_task.py", line 78, in start
  File "modules\exp\normal_task\exp_normal_task.py", line 108, in start_fight
  File "modules\exp\normal_task\exp_normal_task.py", line 352, in start_choose_side_team
KeyError: 1

**Comment by KilluaaaCHEN** [comment]
已修复 更新到v2.0.4
